[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]
asyncio_mode="auto"


filterwarnings = [
    "error",
    "ignore::Warning",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:function ham\(\) is deprecated:DeprecationWarning',
]
